import streamlit as st
import requests
import json

# ── Page config ────────────────────────────────────────────────
st.set_page_config(
    page_title="Concrete Strength Predictor",
    page_icon="🧱",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ── Custom CSS ─────────────────────────────────────────────────
# Streamlit has default styling we override for a cleaner look
st.markdown("""
    <style>
        .block-container { padding-top: 2rem; padding-bottom: 2rem; }
        .metric-card {
            background: #1E1E1E;
            border: 1px solid #2E2E2E;
            border-radius: 10px;
            padding: 20px 24px;
            text-align: center;
        }
        .metric-value {
            font-size: 2.8rem;
            font-weight: 700;
            color: #F0F0F0;
            font-family: monospace;
            line-height: 1.1;
        }
        .metric-label {
            font-size: 0.78rem;
            color: #888;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            margin-bottom: 8px;
        }
        .metric-unit  { font-size: 1rem; color: #888; }
        .winner-tag   {
            display: inline-block;
            background: rgba(200,169,110,0.12);
            color: #C8A96E;
            border: 1px solid #7A6540;
            font-size: 0.7rem;
            padding: 3px 10px;
            border-radius: 20px;
            margin-top: 8px;
            letter-spacing: 0.06em;
        }
        .category-tag {
            font-size: 0.78rem;
            color: #888;
            margin-top: 6px;
        }
        div[data-testid="stNumberInput"] label {
            font-size: 0.82rem;
            color: #aaa;
        }
    </style>
""", unsafe_allow_html=True)


# ── Constants ──────────────────────────────────────────────────
API_URL = "http://backend:8000/predict"


# ── Helper functions ───────────────────────────────────────────
def strength_category(mpa: float) -> str:
    """Return a human-readable label for a given MPa value."""
    if mpa < 20:  return "Low strength"
    if mpa < 40:  return "Moderate strength"
    if mpa < 60:  return "Good structural strength"
    return "High strength"


def strength_color(mpa: float) -> str:
    """Return a color hex for the strength category."""
    if mpa < 20:  return "#E05A5A"
    if mpa < 40:  return "#E0A05A"
    if mpa < 60:  return "#C8A96E"
    return "#4CAF82"


def call_api(payload: dict) -> dict:
    """Send POST request to FastAPI backend and return JSON response."""
    response = requests.post(
        API_URL,
        headers={"Content-Type": "application/json"},
        data=json.dumps(payload),
        timeout=10
    )
    response.raise_for_status()   # raises exception if status != 200
    return response.json()


# ── Header ─────────────────────────────────────────────────────
st.markdown("# 🧱 Concrete Strength Predictor")
st.markdown(
    "Enter your concrete mix parameters below. "
    "Predictions are generated by a **Linear Regression** model "
    "and a **PyTorch MLP**, both trained on the "
    "[UCI Concrete Dataset](https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength)."
)
st.markdown("---")

# ── Layout: two columns ────────────────────────────────────────
left_col, right_col = st.columns([1, 1], gap="large")


# ── Left Column: Input Form ────────────────────────────────────
with left_col:
    st.markdown("### ⚗️ Mix Parameters")
    st.caption("All values in kg/m³ except Age (days)")

    # Row 1
    c1, c2 = st.columns(2)
    with c1:
        cement = st.number_input(
            "Cement (kg/m³)",
            min_value=0.0, max_value=600.0,
            value=350.0, step=1.0,
            help="Mass of cement component"
        )
    with c2:
        water = st.number_input(
            "Water (kg/m³)",
            min_value=0.0, max_value=400.0,
            value=180.0, step=1.0,
            help="Mass of water component"
        )

    # Row 2
    c3, c4 = st.columns(2)
    with c3:
        slag = st.number_input(
            "Blast Furnace Slag (kg/m³)",
            min_value=0.0, max_value=400.0,
            value=0.0, step=1.0,
            help="Can be 0 if not used"
        )
    with c4:
        fly_ash = st.number_input(
            "Fly Ash (kg/m³)",
            min_value=0.0, max_value=300.0,
            value=0.0, step=1.0,
            help="Can be 0 if not used"
        )

    # Row 3
    c5, c6 = st.columns(2)
    with c5:
        superplasticizer = st.number_input(
            "Superplasticizer (kg/m³)",
            min_value=0.0, max_value=50.0,
            value=6.4, step=0.1,
            help="Can be 0 if not used"
        )
    with c6:
        age = st.number_input(
            "Age (days)",
            min_value=1, max_value=365,
            value=28, step=1,
            help="Curing age of concrete"
        )

    # Row 4
    c7, c8 = st.columns(2)
    with c7:
        coarse_agg = st.number_input(
            "Coarse Aggregate (kg/m³)",
            min_value=0.0, max_value=1200.0,
            value=1050.0, step=1.0
        )
    with c8:
        fine_agg = st.number_input(
            "Fine Aggregate (kg/m³)",
            min_value=0.0, max_value=1000.0,
            value=800.0, step=1.0
        )

    st.markdown("")  # spacing

    # ── Predict button ─────────────────────────────────────────
    predict_clicked = st.button(
        "⚡ Predict Compressive Strength",
        type="primary",
        use_container_width=True
    )


# ── Right Column: Results ──────────────────────────────────────
with right_col:
    st.markdown("### 📊 Predictions")

    if not predict_clicked:
        # Idle state
        st.info("Fill in the mix parameters on the left and click **Predict** to see results.")

    else:
        # Build payload — field names must match Pydantic schema exactly
        payload = {
            "cement":             cement,
            "blast_furnace_slag": slag,
            "fly_ash":            fly_ash,
            "water":              water,
            "superplasticizer":   superplasticizer,
            "coarse_aggregate":   coarse_agg,
            "fine_aggregate":     fine_agg,
            "age":                float(age),
        }

        # ── API call with spinner ──────────────────────────────
        with st.spinner("Running models..."):
            try:
                result = call_api(payload)

            except requests.exceptions.ConnectionError:
                st.error(
                    "❌ Could not connect to the API. "
                    "Make sure the FastAPI backend is running on `localhost:8000`."
                )
                st.stop()

            except requests.exceptions.HTTPError as e:
                st.error(f"❌ API returned an error: {e}")
                st.stop()

            except Exception as e:
                st.error(f"❌ Unexpected error: {e}")
                st.stop()

        # ── Unpack results ─────────────────────────────────────
        lr_mpa     = result["linear_regression_mpa"]
        mlp_mpa    = result["mlp_mpa"]
        winner     = result["stronger_model"]

        # ── Model result cards (HTML inside st.markdown) ───────
        lr_winner_tag  = '<div class="winner-tag">HIGHER PREDICTION</div>' \
                         if winner == "Linear Regression" else ""
        mlp_winner_tag = '<div class="winner-tag">HIGHER PREDICTION</div>' \
                         if winner == "MLP" else ""

        r1, r2 = st.columns(2)

        with r1:
            st.markdown(f"""
                <div class="metric-card">
                    <div class="metric-label">Linear Regression</div>
                    <div class="metric-value">
                        {lr_mpa:.2f}
                        <span class="metric-unit">MPa</span>
                    </div>
                    <div class="category-tag">{strength_category(lr_mpa)}</div>
                    {lr_winner_tag}
                </div>
            """, unsafe_allow_html=True)

        with r2:
            st.markdown(f"""
                <div class="metric-card">
                    <div class="metric-label">MLP · Neural Network</div>
                    <div class="metric-value">
                        {mlp_mpa:.2f}
                        <span class="metric-unit">MPa</span>
                    </div>
                    <div class="category-tag">{strength_category(mlp_mpa)}</div>
                    {mlp_winner_tag}
                </div>
            """, unsafe_allow_html=True)

        st.markdown("")

        # ── Bar chart comparison ───────────────────────────────
        st.markdown("**Model Comparison**")

        # Streamlit's built-in progress bar — one line each
        st.caption("Linear Regression")
        st.progress(
            value=min(lr_mpa / 100.0, 1.0),
            text=f"{lr_mpa:.2f} MPa"
        )

        st.caption("MLP · Neural Network")
        st.progress(
            value=min(mlp_mpa / 100.0, 1.0),
            text=f"{mlp_mpa:.2f} MPa"
        )

        # ── Strength scale indicator ───────────────────────────
        st.markdown("")
        avg_mpa = (lr_mpa + mlp_mpa) / 2
        cat     = strength_category(avg_mpa)
        color   = strength_color(avg_mpa)

        st.markdown(
            f'<p style="font-size:0.85rem; color:{color}; font-weight:600;">'
            f'Average prediction: {avg_mpa:.2f} MPa — {cat}</p>',
            unsafe_allow_html=True
        )

        # ── Input echo expander ────────────────────────────────
        with st.expander("View submitted input values"):
            col_a, col_b = st.columns(2)
            items = list(payload.items())
            half  = len(items) // 2

            with col_a:
                for k, v in items[:half]:
                    st.markdown(f"`{k}` → **{v}**")
            with col_b:
                for k, v in items[half:]:
                    st.markdown(f"`{k}` → **{v}**")

        # ── Success message ────────────────────────────────────
        st.success(
            f"✅ Prediction complete. "
            f"**{winner}** predicted higher strength at "
            f"**{max(lr_mpa, mlp_mpa):.2f} MPa**."
        )


# ── Footer ─────────────────────────────────────────────────────
st.markdown("---")
st.caption(
    "UCI Concrete Compressive Strength Dataset · Yeh, I-Cheng (1998) · "
)